server {
    server_name  whistle.musicsian.com;
    root         /var/www/whistle.musicsian.com/current;
    index        index.html;

    access_log  /var/log/nginx/whistle.access.log;
    error_log   /var/log/nginx/whistle.error.log;

    # security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # cache long‑lived assets e.g. /js/, /css/
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }

    listen 80;
}